2017-05-07 04:30:31,200 ERROR Invalid HTTP_HOST header: 'clientapi.ipip.net'. You may need to add u'clientapi.ipip.net' to ALLOWED_HOSTS.
2017-05-07 04:30:50,947 DEBUG POST http://127.0.0.1:53773/wd/hub/session {"capabilities": {"platform": "ANY", "javascriptEnabled": true, "phantomjs.page.settings.loadImages": false, "alwaysMatch": {}, "browserName": "phantomjs", "version": "", "firstMatch": []}, "desiredCapabilities": {"phantomjs.page.settings.loadImages": false, "platform": "ANY", "browserName": "phantomjs", "version": "", "javascriptEnabled": true}}
2017-05-07 04:30:51,010 DEBUG Finished Request
2017-05-07 04:30:51,276 ERROR Internal Server Error: /
Traceback (most recent call last):
  File "C:\virtualenvs\myenv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\virtualenvs\myenv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\virtualenvs\myenv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\virtualenvs\myenv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\virtualenvs\myenv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\virtualenvs\myenv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\virtualenvs\myenv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\virtualenvs\myenv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\virtualenvs\myenv\lib\site-packages\rest_framework\decorators.py", line 52, in handler
    return func(*args, **kwargs)
  File ".\tracer1\views.py", line 133, in welcome
    message = request.GET['q']
  File "C:\virtualenvs\myenv\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'q'"
2017-05-07 22:38:14,775 DEBUG POST http://127.0.0.1:53842/wd/hub/session {"capabilities": {"platform": "ANY", "javascriptEnabled": true, "phantomjs.page.settings.loadImages": false, "alwaysMatch": {}, "browserName": "phantomjs", "version": "", "firstMatch": []}, "desiredCapabilities": {"phantomjs.page.settings.loadImages": false, "platform": "ANY", "browserName": "phantomjs", "version": "", "javascriptEnabled": true}}
2017-05-07 22:38:14,868 DEBUG Finished Request
2017-05-07 22:38:20,392 WARNING Not Found: /index.action
2017-05-07 22:38:30,960 WARNING Not Found: /index.action
2017-05-07 22:38:32,203 DEBUG POST http://127.0.0.1:53856/wd/hub/session {"capabilities": {"platform": "ANY", "javascriptEnabled": true, "phantomjs.page.settings.loadImages": false, "alwaysMatch": {}, "browserName": "phantomjs", "version": "", "firstMatch": []}, "desiredCapabilities": {"phantomjs.page.settings.loadImages": false, "platform": "ANY", "browserName": "phantomjs", "version": "", "javascriptEnabled": true}}
2017-05-07 22:38:32,266 DEBUG Finished Request
2017-05-07 22:38:32,296 WARNING Not Found: /index.action
2017-05-07 22:38:32,861 WARNING Not Found: /index.action
2017-05-07 22:38:33,437 WARNING Not Found: /index.action
2017-05-07 22:38:33,624 WARNING Not Found: /index.action
